apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:foobar@postgresql/kratos?sslmode=disable"

---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: pgweb
