apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pgweb
  name: pgweb
spec:
  containers:
    - image: sosedoff/pgweb
      name: pgweb
      ports:
        - containerPort: 8081
      env:
        - name: DATABASE_URL
          value: postgres://postgres:foobar@postgresql:5432/kratos?sslmode=disable
