apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailslurper
  labels:
    app: mailslurper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailslurper
  template:
    metadata:
      labels:
        app: mailslurper
    spec:
      containers:
      - name: mailslurper
        image: oryd/mailslurper:latest-smtps
        ports:
        - containerPort: 4436
---
apiVersion: v1
kind: Service
metadata:
  name: mailslurper
spec:
  ports:
  - port: 80
    targetPort: 4436
    protocol: TCP
  selector:
    app: mailslurper
